### ISSUE TITLE
unable to ng serve

### ISSUE THREAD

**Issue by Ammonix** [cht8687/angular-redux-starter-kit#1]
when i run
`ng serve`

i get this error:

`
Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (D:\dev\xapp\angular-redux-starter-kit\node_modules\@angular\cli\tasks\serve.js:51:63)
    at check_port_1.checkPort.then.port (D:\dev\xapp\angular-redux-starter-kit\node_modules\@angular\cli\commands\serve.js:123:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
`

**Comment by cht8687** [comment]
@Ammonix 

Have you executed `npm install`?

**Comment by Ammonix** [comment]
@cht8687
yes i did, this is what i tried:

```bash
USER MINGW64 /d/dev
$ git clone https://github.com/cht8687/angular-redux-starter-kit
Cloning into 'angular-redux-starter-kit'...
remote: Counting objects: 68, done.
remote: Total 68 (delta 0), reused 0 (delta 0), pack-reused 68
Unpacking objects: 100% (68/68), done.

USER MINGW64 /d/dev
$ cd angular-redux-starter-kit/

USER MINGW64 /d/dev/angular-redux-starter-kit (master)
$ npm i

> node-sass@4.7.2 install D:\dev\angular-redux-starter-kit\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\USER\AppData\Roaming\npm-cache\node-sass\4.7.2\win32-x64-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall D:\dev\angular-redux-starter-kit\node_modules\webpack\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.7.2 postinstall D:\dev\angular-redux-starter-kit\node_modules\node-sass
> node scripts/build.js

Binary found at D:\dev\angular-redux-starter-kit\node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1179 packages in 49.718s

USER MINGW64 /d/dev/angular-redux-starter-kit (master)
$ ng serve --port 4300
Your global Angular CLI version (1.6.7) is greater than your local
version (1.6.3). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (D:\dev\angular-redux-starter-kit\node_modules\@angular\cli\tasks\serve.js:51:63)
    at check_port_1.checkPort.then.port (D:\dev\angular-redux-starter-kit\node_modules\@angular\cli\commands\serve.js:123:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
i really wanna use this startup template, i think its a great idea

**Comment by Ammonix** [comment]
running
``` cmd
ng --verbose
```
doesn't give me more information
``` cmd
ng serve --verbose
Your global Angular CLI version (1.6.7) is greater than your local
version (1.6.3). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (D:\dev\angular-redux-starter-kit\node_modules\@angular\cli\tasks\serve.js:51:63)
    at check_port_1.checkPort.then.port (D:\dev\angular-redux-starter-kit\node_modules\@angular\cli\commands\serve.js:123:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by cht8687** [comment]
@Ammonix 
oops. forgot to commit .angular-cli.json.

Try it now. I've fixed it.

**Comment by Ammonix** [comment]
works, thank you
